# -*- coding: utf-8 -*-
"""Calcula-Dobro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOMtvviXBvJr2dnH1YhZTrIDWHaQc5_X
"""

numero = int(input("Informe um número: "))
dobro = numero * 2
print("Dobro = ", dobro)